import Head from 'next/head'
import styles from '../styles/About.module.css'



export default function About() {
    return (
        <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        This is the main area.
      </main>
    </>
  )
}